version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: unless-stopped
